defaults:
  - benchmark
  - scenario: inference
  - launcher: process
  - backend: pytorch
  - _base_
  - _self_

name: llama3_8b_bf16

backend:
  model: meta-llama/Llama-3.1-8B
  torch_dtype: bfloat16
  no_weights: false

scenario:
  input_shapes:
    batch_size: 1
    sequence_length: 512
  generate_kwargs:
    max_new_tokens: 128
    min_new_tokens: 128
